name: CI - Validaciones

on:
  push:
    branches:
      - main
      - development
      - backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint || echo "Lint warnings, no bloquea"

      - name: Test
        run: |
          npm test || echo "Tests fallidos, revisar"
